apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dotnet-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/vprocopan/dotnet'
    targetRevision: main
    path: k8s

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dotnet

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
