apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet
spec:
  template:
    spec:
      containers:
        - name: dotnet
          image: vprocopan/dotnet:build-27
          imagePullPolicy: Always
